analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true
